spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/jpaboard
    username: root
    password: wkfskrk1!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

  thymeleaf:
    cache: false
    encoding: UTF-8
    mode: HTML
    suffix: .html
    prefix: classpath:/templates/

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace
